<a href="https://colab.research.google.com/github/krishnaprasadlenka/python-/blob/main/numpy_tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("1-d array")#creating 1 d array
a=np.array([1,2,3,4,5])
print(a)

1-d array
[1 2 3 4 5]


In [ ]:
print("2-d array")#creating 2 d array
b=np.array([[1,2,3,4,5],[6,7,8,9,3]])
print(b)

2-d array
[[1 2 3 4 5]
 [6 7 8 9 3]]


In [ ]:
print("3-d-array")#creating 3 d array
c=np.array([[[1,2,3],[4,5,6],[8,9,3]]])
print(c)

3-d-array
[[[1 2 3]
  [4 5 6]
  [8 9 3]]]


In [ ]:
print(a.dtype)#for finding the datatype

int64


In [ ]:
print(a.transpose())

[1 2 3 4 5]


In [ ]:
print(b.transpose())#for finding the transpose

[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 3]]


In [ ]:

np.empty((5,7),dtype=int)#for creating a matrix without initializing values


array([[          939251044,                   0, 2334382411600589939,
        2308669249719853428, 7307218076785713184, 7311348139908099360,
        8388367117302723111],
       [8031079664114559075, 8295665835965024814, 7599669539435734376,
        8386669407982084980, 7306087011045372773, 7237123112367517224,
        2314861246702823781],
       [8245937343108948000, 8029109407846375525, 7575164998475867492,
        2308669224168416878, 8245937481688555552, 4404631917608906341,
        8029399631839322656],
       [ 732227896464973940, 7237123110953033738, 2336353779914137445,
        2830026721625579581, 7231476050072381228, 8029124723917943923,
        2314885435964089700],
       [2821633184111947808, 2338620986093694788, 4211825664382496621,
        6874010835985902631,    2860295301259628, 8746391181558637600,
                        304]])

In [ ]:

# numpy.ones method

import numpy as np

b = np.ones(2, dtype = int)
print("Matrix b : \n", b)

a = np.ones([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = np.ones([3, 3])
print("\nMatrix c : \n", c)


Matrix b : 
 [1 1]

Matrix a : 
 [[1 1]
 [1 1]]

Matrix c : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((6,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4),dtype=str)#representing in form of strings

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [ ]:
np.ones((3,4),dtype=str)#representing in form of strings

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [ ]:
a=np.arange(1,20,2)#creating an array with specific interval(np.arange(start,end,step))
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
#np.reshape((rows, cols))
a=a.reshape((2,5))
print(a)

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [ ]:
#with bigger number
b=np.arange(1,100,2)
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))  # Reshape into 2 rows and 3 columns
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

a = np.arange(1, 101, 1)
print(a)
b = a.reshape((10, 10))  # Corrected reshape dimensions
print(b)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [ ]:
b=b.flatten()#reverse process of reshape
print(b)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
a=a.ravel()#give the reference view of original array
print(a)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
import numpy as np
a=np.arange(1,51)
a=a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [ ]:
a[0]#is going to give the first array

array([1, 2, 3, 4, 5])

In [ ]:
a[0,0]

np.int64(1)

In [ ]:
a[3,4]#3rd row 4th column

np.int64(20)

In [ ]:
a[2:4]#will print the row from 2nd index and 3rd index

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
a[:,4]#colon represents all the rows and 4 represnts of 4th column

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
a[2:5,4]

array([15, 20, 25])

In [ ]:
a[2:5,4].dtype

dtype('int64')

In [ ]:
import numpy as np
a=np.arange(0,18).reshape((6,3))
b=np.arange(20,38).reshape((6,3))
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [ ]:
a+b#traditional format

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [ ]:
np.add(a,b)#function

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [ ]:
np.subtract(a,b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [ ]:
np.multiply(a,b)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [ ]:
np.divide(a,b)

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [ ]:
 print(a.shape)
 print(b.shape)

(6, 3)
(6, 3)


In [ ]:
b=b.reshape((3,6))

In [ ]:
a@b#for matrix multiplication

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [ ]:
a.dot(b)#it will also give the same result as above

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [ ]:
b.max()#maximum of particular array

np.int64(37)

In [ ]:
b.min()#minimum of particular array

np.int64(20)

In [ ]:
a.max()

np.int64(17)

In [ ]:
a.min()

np.int64(0)

In [ ]:
b.argmax()#index of maximum value in array

np.int64(17)

In [ ]:
np.sum(b)

np.int64(513)

In [ ]:
np.sum(b,axis=1)#gives sum of elements in rows

array([135, 171, 207])

In [ ]:
np.sum(b,axis=0)#gives sum of elements in columns

array([78, 81, 84, 87, 90, 93])

In [ ]:
np.mean(b)#gives mean of the array

np.float64(28.5)

In [ ]:
np.sqrt(b)#for finding the square root

array([[4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        ],
       [5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
        5.56776436],
       [5.65685425, 5.74456265, 5.83095189, 5.91607978, 6.        ,
        6.08276253]])

In [ ]:
np.std(b)#for finding the standard deviation

np.float64(5.188127472091127)